apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "fernando.navarro@bairesdev.com"  
    privateKeySecretRef:
      name: letsencrypt-production-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: nginx
